# Generated by Django 5.2.18 on 2026-10-07 06:41

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Large landscape photo, at least 1920x1080 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('hero'), upload_to='hero', verbose_name='Background image')),
                ('background_image_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Background image description')),
                ('heading', models.CharField(default='Connecting Indian Tamils Across', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='London & the UK', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('description', models.TextField(blank=True, default='London Indian Tamils (LIT) is a growing community bringing together Tamil-speaking people of Indian origin living across the UK.', verbose_name='Main description')),
                ('sub_description', models.TextField(blank=True, default='Meet people. Make friends. Discover opportunities. Support one another. Celebrate our culture.', verbose_name='Smaller description')),
                ('primary_button_text', models.CharField(blank=True, default='JOIN LIT', max_length=50, verbose_name='Main button text')),
                ('primary_button_link', models.CharField(blank=True, help_text='Leave empty to open the Join LIT Google Form (set in Site Settings).', max_length=500, verbose_name='Main button link')),
                ('secondary_button_text', models.CharField(blank=True, default='VIEW EVENTS', max_length=50, verbose_name='Second button text')),
                ('secondary_button_link', models.CharField(blank=True, default='#events', max_length=500, verbose_name='Second button link')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('logo', models.ImageField(blank=True, help_text='Round logo shown at the top left. PNG with transparent background works best.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('navbar'), upload_to='navbar', verbose_name='Logo')),
                ('logo_alt_text', models.CharField(default='London Indian Tamils (LIT) logo', help_text='Read out by screen readers and used by Google.', max_length=150, verbose_name='Logo description')),
                ('brand_name', models.CharField(default='London Indian Tamils', max_length=100, verbose_name='Organisation name')),
                ('brand_highlight', models.CharField(blank=True, default='(LIT)', help_text='Shown in the accent colour next to the organisation name.', max_length=50, verbose_name='Highlighted name')),
                ('tagline', models.CharField(blank=True, default='CONNECT • SUPPORT • CELEBRATE', max_length=150, verbose_name='Tagline')),
                ('sub_tagline', models.CharField(blank=True, default='India in our heart. London in our home. Tamil in our identity.', max_length=200, verbose_name='Small text under tagline')),
                ('show_button', models.BooleanField(default=True, verbose_name='Show button')),
                ('button_text', models.CharField(default='JOIN LIT', max_length=50, verbose_name='Button text')),
                ('button_link', models.CharField(blank=True, help_text='Leave empty to open the Join LIT Google Form (set in Site Settings).', max_length=500, verbose_name='Button link')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('site_title', models.CharField(default='London Indian Tamils (LIT)', help_text='Shown in the browser tab and search results.', max_length=150, verbose_name='Website title')),
                ('meta_description', models.TextField(blank=True, help_text='A short summary (about 150 characters) shown by Google.', verbose_name='Search engine description')),
                ('favicon', models.ImageField(blank=True, help_text='Square image, e.g. 64x64 PNG.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('site'), upload_to='site', verbose_name='Browser tab icon (favicon)')),
                ('join_form_url', models.URLField(blank=True, help_text='Every "JOIN LIT" button opens this form in a new tab. Paste the link from Google Forms → Send → link icon.', max_length=500, verbose_name='Join LIT Google Form link')),
                ('notification_email', models.EmailField(blank=True, help_text='Form submissions from the website are sent to this address.', max_length=254, verbose_name='Enquiry notification email')),
                ('use_cloudinary', models.BooleanField(default=True, help_text='When off (or details are missing), images are stored on this server.', verbose_name='Upload images to Cloudinary')),
                ('cloudinary_cloud_name', models.CharField(blank=True, max_length=100, verbose_name='Cloud name')),
                ('cloudinary_api_key', models.CharField(blank=True, max_length=100, verbose_name='API key')),
                ('cloudinary_api_secret', models.CharField(blank=True, max_length=150, verbose_name='API secret')),
                ('smtp_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=150, verbose_name='SMTP server')),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='587 for TLS, 465 for SSL.', verbose_name='SMTP port')),
                ('smtp_username', models.CharField(blank=True, max_length=150, verbose_name='SMTP username')),
                ('smtp_password', models.CharField(blank=True, help_text='For Gmail, use an App Password, not your normal password.', max_length=150, verbose_name='SMTP password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('from_email', models.EmailField(blank=True, help_text='Usually the same as the SMTP username.', max_length=254, verbose_name='Send emails from')),
                ('from_name', models.CharField(default='London Indian Tamils (LIT)', max_length=100, verbose_name='Sender name')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.herosection')),
            ],
            options={
                'verbose_name': 'Badge word',
                'verbose_name_plural': 'Badge words (shown above the heading, separated by dots)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('label', models.CharField(max_length=50, verbose_name='Menu text')),
                ('link', models.CharField(help_text='Use #section-name to scroll to a section (e.g. #about), or a full web address.', max_length=255, verbose_name='Link')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open in new tab')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.navbar')),
            ],
            options={
                'verbose_name': 'Menu link',
                'verbose_name_plural': 'Menu links',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
