# Generated by Django 5.2.18 on 2026-10-07 06:46

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('section_label', models.CharField(blank=True, default='ABOUT LIT', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default='More Than a WhatsApp Group.', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='A Community.', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('paragraph_1', models.TextField(blank=True, verbose_name='First paragraph')),
                ('paragraph_2', models.TextField(blank=True, verbose_name='Second paragraph')),
                ('image', models.ImageField(blank=True, help_text='Portrait photo shown on the left, about 800x1000 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('about'), upload_to='about', verbose_name='Photo')),
                ('image_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Photo description')),
                ('badge_title', models.CharField(blank=True, default='தமிழ்', help_text='The small card on the corner of the photo. Leave empty to hide it.', max_length=50, verbose_name='Photo badge - big text')),
                ('badge_subtitle', models.CharField(blank=True, default='ONE COMMUNITY', max_length=50, verbose_name='Photo badge - small text')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('icon', models.CharField(choices=[('users', 'People / Connect'), ('heart-handshake', 'Heart handshake / Support'), ('sparkles', 'Sparkles / Celebrate'), ('handshake', 'Handshake'), ('heart', 'Heart'), ('star', 'Star'), ('calendar', 'Calendar / Events'), ('briefcase', 'Briefcase / Careers'), ('graduation-cap', 'Graduation cap / Education'), ('trophy', 'Trophy / Sports'), ('music', 'Music'), ('utensils', 'Food'), ('globe', 'Globe'), ('map-pin', 'Location'), ('home', 'Home'), ('book-open', 'Book'), ('camera', 'Camera'), ('message-circle', 'Chat'), ('phone', 'Phone'), ('mail', 'Email')], default='users', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Gives this card the gold border and gold title.', verbose_name='Highlight')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards (Connect / Support / Celebrate) - numbers 01, 02, 03 are added automatically',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
