# Generated by Django 5.2.18 on 2026-10-07 06:46

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutsection_aboutpillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='The patterned background behind the whole section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('about'), upload_to='about', verbose_name='Section background image'),
        ),
    ]
