# Generated by Django 5.2.18 on 2026-10-07 06:49

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('community'), upload_to='community', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='OUR COMMUNITY', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default="There's Something", max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='for Everyone', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
            ],
            options={
                'verbose_name': 'Community Section',
                'verbose_name_plural': 'Community Section',
            },
        ),
        migrations.AlterField(
            model_name='aboutpillar',
            name='icon',
            field=models.CharField(choices=[('users', 'People / Connect'), ('heart-handshake', 'Heart handshake / Support'), ('sparkles', 'Sparkles / Celebrate'), ('handshake', 'Handshake'), ('heart', 'Heart'), ('star', 'Star'), ('calendar', 'Calendar / Events'), ('briefcase', 'Briefcase / Careers'), ('store', 'Shop front / Business'), ('shopping-bag', 'Shopping bag / Marketplace'), ('party-popper', 'Party popper'), ('calendar-heart', 'Calendar with heart / Events'), ('graduation-cap', 'Graduation cap / Education'), ('trophy', 'Trophy / Sports'), ('music', 'Music'), ('utensils', 'Food'), ('globe', 'Globe'), ('map-pin', 'Location'), ('home', 'Home'), ('book-open', 'Book'), ('camera', 'Camera'), ('message-circle', 'Chat'), ('phone', 'Phone'), ('mail', 'Email')], default='users', max_length=50, verbose_name='Icon'),
        ),
        migrations.CreateModel(
            name='CommunityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.communitysection')),
            ],
            options={
                'verbose_name': 'Highlight word',
                'verbose_name_plural': 'Highlight words (gold line at the top, separated by dots)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('icon', models.CharField(choices=[('users', 'People / Connect'), ('heart-handshake', 'Heart handshake / Support'), ('sparkles', 'Sparkles / Celebrate'), ('handshake', 'Handshake'), ('heart', 'Heart'), ('star', 'Star'), ('calendar', 'Calendar / Events'), ('briefcase', 'Briefcase / Careers'), ('store', 'Shop front / Business'), ('shopping-bag', 'Shopping bag / Marketplace'), ('party-popper', 'Party popper'), ('calendar-heart', 'Calendar with heart / Events'), ('graduation-cap', 'Graduation cap / Education'), ('trophy', 'Trophy / Sports'), ('music', 'Music'), ('utensils', 'Food'), ('globe', 'Globe'), ('map-pin', 'Location'), ('home', 'Home'), ('book-open', 'Book'), ('camera', 'Camera'), ('message-circle', 'Chat'), ('phone', 'Phone'), ('mail', 'Email')], default='users', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.communitysection')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards - numbers 01, 02, 03... are added automatically',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
