# Generated by Django 5.2.18 on 2026-10-07 06:52

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_communitysection_alter_aboutpillar_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('badge_text', models.CharField(blank=True, default='FEATURED EVENT', help_text='Small outlined label above the title. Leave empty to hide.', max_length=50, verbose_name='Badge')),
                ('title', models.CharField(max_length=150, verbose_name='Event name')),
                ('title_highlight', models.CharField(blank=True, help_text='Shown in gold on its own line, e.g. the year.', max_length=50, verbose_name='Highlighted part of name')),
                ('background_image', models.ImageField(blank=True, help_text='Landscape photo, at least 1600x800 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('events'), upload_to='events', verbose_name='Event background image')),
                ('background_image_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Image description')),
                ('banner_icon', models.CharField(blank=True, choices=[('users', 'People / Connect'), ('heart-handshake', 'Heart handshake / Support'), ('sparkles', 'Sparkles / Celebrate'), ('handshake', 'Handshake'), ('heart', 'Heart'), ('star', 'Star'), ('calendar', 'Calendar / Events'), ('briefcase', 'Briefcase / Careers'), ('store', 'Shop front / Business'), ('shopping-bag', 'Shopping bag / Marketplace'), ('party-popper', 'Party popper'), ('calendar-heart', 'Calendar with heart / Events'), ('graduation-cap', 'Graduation cap / Education'), ('trophy', 'Trophy / Sports'), ('music', 'Music'), ('utensils', 'Food'), ('globe', 'Globe'), ('map-pin', 'Location'), ('home', 'Home'), ('book-open', 'Book'), ('camera', 'Camera'), ('message-circle', 'Chat'), ('phone', 'Phone'), ('mail', 'Email')], default='music', max_length=50, verbose_name='Banner icon')),
                ('banner_text', models.CharField(blank=True, help_text='The big gold strip, e.g. the performer. Leave empty to hide.', max_length=100, verbose_name='Banner text')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='Venue')),
                ('venue_map_link', models.URLField(blank=True, help_text='Optional Google Maps link - the venue becomes clickable.', max_length=500, verbose_name='Venue map link')),
                ('ticket_info', models.CharField(blank=True, max_length=150, verbose_name='Ticket information')),
                ('button_text', models.CharField(blank=True, default='BOOK NOW', max_length=50, verbose_name='Button text')),
                ('button_link', models.CharField(blank=True, help_text='Leave empty to open the Join LIT Google Form (set in Site Settings).', max_length=500, verbose_name='Button link')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('events'), upload_to='events', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='EVENTS', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default='Meet. Celebrate.', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='Connect.', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('description', models.TextField(blank=True, default='LIT brings our online community together through real-world experiences.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Events Section',
                'verbose_name_plural': 'Events Section',
            },
        ),
        migrations.CreateModel(
            name='EventFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.event')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features (line under the banner, separated by dots)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventsHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.eventssection')),
            ],
            options={
                'verbose_name': 'Highlight word',
                'verbose_name_plural': 'Highlight words (gold line under the description, separated by dots)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
