# Generated by Django 5.2.18 on 2026-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_eventssection_eventfeature_eventshighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_note',
            field=models.CharField(blank=True, help_text='Shown in smaller text after the ticket information, e.g. (food and drinks not included.)', max_length=150, verbose_name='Ticket note (small text)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255, verbose_name='Venue / pick-up'),
        ),
    ]
