# Generated by Django 5.2.18 on 2026-10-07 06:57

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_ticket_note_alter_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show floating buttons')),
                ('show_call', models.BooleanField(default=True, verbose_name='Show call button')),
                ('phone_number', models.CharField(blank=True, help_text='With country code, e.g. +44 7700 900123. Leave empty to hide the button.', max_length=30, verbose_name='Phone number')),
                ('show_email', models.BooleanField(default=True, verbose_name='Show email button')),
                ('email', models.EmailField(blank=True, help_text='Leave empty to hide the button.', max_length=254, verbose_name='Email address')),
                ('email_subject', models.CharField(blank=True, default='Enquiry from LIT website', max_length=150, verbose_name='Email subject')),
                ('show_whatsapp', models.BooleanField(default=True, verbose_name='Show WhatsApp button')),
                ('whatsapp_number', models.CharField(blank=True, help_text='With country code, e.g. +44 7700 900123. Leave empty to hide the button.', max_length=30, verbose_name='WhatsApp number')),
                ('whatsapp_message', models.CharField(blank=True, default='Hi LIT, I would like to know more about London Indian Tamils.', help_text='Pre-filled in the chat when someone taps the button.', max_length=300, verbose_name='WhatsApp starting message')),
            ],
            options={
                'verbose_name': 'Floating Contact Buttons',
                'verbose_name_plural': 'Floating Contact Buttons',
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('gallery'), upload_to='gallery', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='FOLLOW US', max_length=50, verbose_name='Small label above heading')),
                ('heading_highlight', models.CharField(blank=True, default='LIT', help_text='Shown in gold BEFORE the heading.', max_length=100, verbose_name='Highlighted heading')),
                ('heading', models.CharField(default='Community Moments', max_length=200, verbose_name='Heading')),
                ('instagram_handle', models.CharField(blank=True, default='@LondonIndianTamils', help_text='Button text at the top right. Leave empty to hide the button.', max_length=100, verbose_name='Instagram name')),
                ('instagram_link', models.URLField(blank=True, default='https://www.instagram.com/londonindiantamils/', max_length=500, verbose_name='Instagram link')),
            ],
            options={
                'verbose_name': 'Gallery Section',
                'verbose_name_plural': 'Gallery Section',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('image', models.ImageField(blank=True, max_length=500, storage=core.storage.CloudinaryOrLocalStorage('gallery'), upload_to='gallery', verbose_name='Photo')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Photo description')),
                ('size', models.CharField(choices=[('small', 'Small (square)'), ('medium', 'Medium (square)'), ('large', 'Large (tall, centre photo)')], default='medium', help_text='The design uses: Medium, Small, Large, Small, Medium.', max_length=10, verbose_name='Size')),
                ('link', models.URLField(blank=True, help_text='e.g. the Instagram post. Leave empty to use the Instagram link above.', max_length=500, verbose_name='Link (optional)')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.gallerysection')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
