# Generated by Django 5.2.18 on 2026-10-07 07:04

import core.models.base
import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_floatingbuttons_gallerysection_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('messages'), upload_to='messages', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='VOICES OF SUPPORT', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default='Messages to the', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='LIT Community', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('follow_text_before', models.CharField(blank=True, default='Follow', max_length=100, verbose_name='Follow line - text before')),
                ('follow_handle', models.CharField(blank=True, default='@londonindiantamils', help_text='Shown in gold and links to Instagram. Leave all three parts empty to hide the line.', max_length=100, verbose_name='Follow line - Instagram name')),
                ('follow_text_after', models.CharField(blank=True, default='for more community stories, messages and updates.', max_length=200, verbose_name='Follow line - text after')),
                ('follow_link', models.URLField(blank=True, default='https://www.instagram.com/londonindiantamils/', max_length=500, verbose_name='Instagram link')),
            ],
            options={
                'verbose_name': 'Messages Section',
                'verbose_name_plural': 'Messages Section',
            },
            bases=(core.models.base.SharedBackgroundMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('photo', models.ImageField(blank=True, help_text='Portrait photo, about 600x800 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('messages'), upload_to='messages', verbose_name='Photo')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Role / title')),
                ('status_text', models.CharField(blank=True, default='Message coming soon', help_text='Small gold text under the role. Clear it once the video is added.', max_length=100, verbose_name='Status text')),
                ('button_text', models.CharField(blank=True, default='Watch Message', max_length=50, verbose_name='Button text')),
                ('video_link', models.URLField(blank=True, help_text='YouTube, Instagram or Cloudinary video link. Leave empty and the button opens the Instagram page.', max_length=500, verbose_name='Video link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.messagessection')),
            ],
            options={
                'verbose_name': 'Message card',
                'verbose_name_plural': 'Message cards',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
