# Generated by Django 5.2.18 on 2026-10-07 07:07

import core.models.base
import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_messagessection_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('join'), upload_to='join', verbose_name='Section background image')),
                ('banner_image', models.ImageField(blank=True, help_text='Wide photo inside the rounded banner, at least 1800x700 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('join'), upload_to='join', verbose_name='Banner photo')),
                ('banner_image_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Banner photo description')),
                ('heading', models.CharField(default='Join', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='London Indian Tamils', help_text='Shown in the accent colour (italic) after the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('subheading', models.CharField(blank=True, default='Tamil-speaking Indian living in the UK?', max_length=200, verbose_name='Question line')),
                ('description', models.CharField(blank=True, default='Become part of our growing community.', max_length=200, verbose_name='Line under the question')),
                ('button_text', models.CharField(blank=True, default='JOIN NOW', max_length=50, verbose_name='Button text')),
                ('button_link', models.CharField(blank=True, help_text='Leave empty to open the Join LIT Google Form (set in Site Settings).', max_length=500, verbose_name='Button link')),
            ],
            options={
                'verbose_name': 'Join Section',
                'verbose_name_plural': 'Join Section',
            },
            bases=(core.models.base.SharedBackgroundMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('social'), upload_to='social', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='SOCIAL MEDIA', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default='Stay Connected', max_length=200, verbose_name='Heading')),
                ('heading_highlight', models.CharField(blank=True, default='With LIT', help_text='Shown in the accent colour (italic) on the line below the heading.', max_length=200, verbose_name='Highlighted heading')),
                ('description', models.TextField(blank=True, default='Follow us for community news, event announcements, photos, videos and activities.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Social Media Section',
                'verbose_name_plural': 'Social Media Section',
            },
            bases=(core.models.base.SharedBackgroundMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JoinBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=60, verbose_name='Text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.joinsection')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits (rounded pills above the button)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], help_text='Sets the icon.', max_length=20, verbose_name='Platform')),
                ('label', models.CharField(blank=True, help_text='e.g. INSTAGRAM', max_length=50, verbose_name='Small label')),
                ('account_name', models.CharField(help_text='e.g. @londonindiantamils', max_length=100, verbose_name='Account name')),
                ('url', models.URLField(blank=True, help_text='Full address of the page, e.g. https://www.facebook.com/...', max_length=500, verbose_name='Link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.socialsection')),
            ],
            options={
                'verbose_name': 'Social account',
                'verbose_name_plural': 'Social accounts',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
