# Generated by Django 5.2.18 on 2026-10-07 07:11

import core.models.base
import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_joinsection_socialsection_joinbenefit_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section')),
                ('background_image', models.ImageField(blank=True, help_text='Leave empty to use the same background as the About section.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('contact'), upload_to='contact', verbose_name='Section background image')),
                ('section_label', models.CharField(blank=True, default='CONTACT', max_length=50, verbose_name='Small label above heading')),
                ('heading', models.CharField(default='London Indian Tamils', max_length=200, verbose_name='Heading')),
                ('location', models.CharField(blank=True, default='London, United Kingdom', max_length=200, verbose_name='Location')),
                ('location_link', models.URLField(blank=True, help_text='Optional Google Maps link - the location becomes clickable.', max_length=500, verbose_name='Location map link')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Shown exactly as typed, e.g. 07940 173183. UK numbers starting with 0 are dialled as +44.', max_length=30, verbose_name='Phone')),
                ('person_name', models.CharField(blank=True, max_length=100, verbose_name='Contact person')),
                ('person_role', models.CharField(blank=True, max_length=100, verbose_name='Contact person role')),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
            bases=(core.models.base.SharedBackgroundMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('brand_name', models.CharField(default='LONDON INDIAN TAMILS', max_length=100, verbose_name='Organisation name')),
                ('tagline', models.CharField(blank=True, default='CONNECT • SUPPORT • CELEBRATE', max_length=150, verbose_name='Tagline')),
                ('quote', models.CharField(blank=True, default='India in our heart. London in our home. Tamil in our identity.', max_length=200, verbose_name='Quote')),
                ('show_social_icons', models.BooleanField(default=True, help_text='Icons come from Social Media Section → accounts ticked "Show in footer".', verbose_name='Show social media icons')),
                ('copyright_text', models.CharField(default='London Indian Tamils. All Rights Reserved.', help_text='"© <current year>" is added in front automatically.', max_length=200, verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.AddField(
            model_name='floatingbuttons',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Leave empty to use the Instagram account in the Social Media section.', max_length=500, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='floatingbuttons',
            name='show_instagram',
            field=models.BooleanField(default=True, verbose_name='Show Instagram button'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='footer_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the icons in the footer.', verbose_name='Footer order'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_in_footer',
            field=models.BooleanField(default=True, verbose_name='Show in footer'),
        ),
        migrations.AlterField(
            model_name='floatingbuttons',
            name='email',
            field=models.EmailField(blank=True, help_text='Leave empty to use the one in the Contact section.', max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='floatingbuttons',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Leave empty to use the one in the Contact section.', max_length=30, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='floatingbuttons',
            name='show_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Show WhatsApp button'),
        ),
        migrations.AlterField(
            model_name='floatingbuttons',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Leave empty to use the Contact section phone number.', max_length=30, verbose_name='WhatsApp number'),
        ),
        migrations.CreateModel(
            name='ContactButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('kind', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('link', 'Other link')], help_text='Sets the icon.', max_length=20, verbose_name='Type')),
                ('label', models.CharField(max_length=50, verbose_name='Button text')),
                ('link', models.CharField(blank=True, help_text='Leave empty: Call/Email use the phone and email above; social buttons use the Social Media section accounts.', max_length=500, verbose_name='Link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.contactsection')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
