# Generated by Django 5.2.18 on 2026-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactsection_footer_floatingbuttons_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpillar',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Keeps the gold border and gold title on all the time (normally they only show on hover).', verbose_name='Highlight'),
        ),
    ]
