# Generated by Django 5.2.18 on 2026-10-07 07:55

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_aboutpillar_is_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Last part of the link, e.g. privacy-policy → /privacy-policy/', max_length=80, unique=True, verbose_name='Web address')),
                ('content', models.TextField(blank=True, help_text='Leave a blank line between paragraphs. Lines starting with "## " become headings.', verbose_name='Content')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Link in footer')),
            ],
            options={
                'verbose_name': 'Page (Privacy Policy, Guidelines...)',
                'verbose_name_plural': 'Pages (Privacy Policy, Guidelines...)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_url',
            field=models.URLField(blank=True, default='https://buytickets.at/LIT', help_text='Every "BOOK NOW" button opens this, unless the event has its own booking link.', max_length=500, verbose_name='Event booking link (Ticket Tailor)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Optional, e.g. G-XXXXXXXXXX. Leave empty for no analytics.', max_length=30, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200x630 px. LIT logo + London imagery + name + tagline. Leave empty to use the logo.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('site'), upload_to='site', verbose_name='Sharing image (WhatsApp / Facebook preview)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='button_link',
            field=models.CharField(blank=True, help_text='Direct Ticket Tailor link for this event. Leave empty to use the main event booking link in Site Settings.', max_length=500, verbose_name='Booking link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='London Indian Tamils (LIT) | Indian Tamil Community in the UK', help_text='Shown in the browser tab and search results.', max_length=150, verbose_name='Website title'),
        ),
    ]
