# Generated by Django 5.2.18 on 2026-10-07 07:58

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_infopage_sitesettings_booking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_photo',
            field=models.ImageField(blank=True, help_text='e.g. the approved photo of the performer. Shown as a round portrait next to the gold banner.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('events'), upload_to='events', verbose_name='Artist / featured photo (optional)'),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_photo_alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Featured photo description'),
        ),
    ]
