# Generated by Django 5.2.18 on 2026-10-07 10:44

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_featured_photo_event_featured_photo_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='founder_bio',
            field=models.TextField(blank=True, default='London Indian Tamils was founded by Sathish Duraisamy with a simple vision - to create a stronger, more connected and supportive community for Tamil-speaking Indians living across the UK.\n\nHaving lived in the UK for many years and been actively involved in community, cultural and social initiatives, Sathish wanted to create a platform that goes beyond events and WhatsApp conversations - a community where people can build friendships, support careers and businesses, share opportunities and celebrate Tamil culture together.\n\nHis vision for LIT is to bring people together across generations, professions and locations, creating meaningful connections and a community that supports one another.', help_text='Leave a blank line between paragraphs. Keep it short - the personal website carries the full story.', verbose_name='Founder introduction'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_button_link',
            field=models.URLField(blank=True, help_text="Sathish's personal website Founder/About page. The button is hidden until a link is added.", max_length=500, verbose_name='Button link'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_button_text',
            field=models.CharField(blank=True, default='ABOUT SATHISH', max_length=50, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_name',
            field=models.CharField(blank=True, default='Sathish Duraisamy', max_length=100, verbose_name='Founder name'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_photo',
            field=models.ImageField(blank=True, help_text='Portrait photo, about 600x750 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('about'), upload_to='about', verbose_name='Founder photo (optional)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_photo_alt_text',
            field=models.CharField(blank=True, default='Sathish Duraisamy, Founder & Director of London Indian Tamils', max_length=200, verbose_name='Founder photo description'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_quote',
            field=models.CharField(blank=True, default='LIT is about people, relationships and creating something valuable for the community - together.', help_text='Quotation marks are added automatically.', max_length=300, verbose_name='Founder quote'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_role',
            field=models.CharField(blank=True, default='Founder & Director, London Indian Tamils', max_length=150, verbose_name='Founder title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='show_founder',
            field=models.BooleanField(default=True, verbose_name='Show founder block'),
        ),
    ]
