# Generated by Django 5.2.18 on 2026-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutsection_founder_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='founder_button_link',
            field=models.URLField(blank=True, help_text="Sathish's personal website Founder/About page (opens in a new tab). While empty, the button scrolls to the Contact section.", max_length=500, verbose_name='Button link'),
        ),
    ]
