# Generated by Django 5.2.18 on 2026-10-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aboutsection_founder_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='founder_photo',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='founder_photo_alt_text',
        ),
    ]
