# Generated by Django 5.2.18 on 2026-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_aboutsection_founder_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsection',
            name='location_link',
            field=models.URLField(blank=True, help_text='Optional. Leave empty to open a Google Maps search for the location above.', max_length=500, verbose_name='Location map link'),
        ),
    ]
