# Generated by Django 5.2.18 on 2026-10-08 04:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contactsection_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='founder_photo',
            field=models.ImageField(blank=True, help_text='Portrait photo shown on the left of the founder block, about 600x750 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('about'), upload_to='about', verbose_name='Founder photo'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='founder_photo_alt_text',
            field=models.CharField(blank=True, default='Sathish Duraisamy, Founder & Director of London Indian Tamils', max_length=200, verbose_name='Founder photo description'),
        ),
    ]
