# Generated by Django 5.2.18 on 2026-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutsection_founder_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='founder_bio',
            field=models.TextField(blank=True, default='London Indian Tamils was founded by Sathish Duraisamy with a simple vision - to create a stronger, more connected and supportive community for Tamil-speaking Indians living across the UK.\n\nHaving lived in the UK for many years and been actively involved in community, cultural and social initiatives, Sathish wanted to create a platform that goes beyond events and WhatsApp conversations - a community where people can build friendships, support careers and businesses, share opportunities and celebrate Tamil culture together.\n\nSathish has been involved in community and cultural initiatives in the UK for many years. He previously served as Secretary of the South Indian Society (SIS) and is also the Founder & Director of I for India and E for Events, through which he has organised and supported a wide range of Indian cultural, social and entertainment activities in the UK.\n\nHis vision for LIT is to bring people together across generations, professions and locations, creating meaningful connections and a community that supports one another.', help_text='Leave a blank line between paragraphs. Keep it short - the personal website carries the full story.', verbose_name='Founder introduction'),
        ),
    ]
