# Generated by Django 5.2.18 on 2026-10-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aboutsection_founder_bio_para3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='founder_button_link',
            field=models.URLField(blank=True, help_text="Sathish's personal website Founder/About page (opens in a new tab). While empty, the button scrolls to the Founder section.", max_length=500, verbose_name='Button link'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='status_text',
            field=models.CharField(blank=True, default='', help_text='Optional small gold text under the role.', max_length=100, verbose_name='Status text'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube, Instagram or Cloudinary video link. The photo and the button both open it. Leave empty and they open the Instagram page.', max_length=500, verbose_name='Video link'),
        ),
    ]
