# Generated by Django 5.2.18 on 2026-10-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_client_content_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='credit_link',
            field=models.URLField(blank=True, default='https://vetriitsystems.com/', help_text='Opens in a new tab.', max_length=500, verbose_name='Credit link'),
        ),
        migrations.AddField(
            model_name='footer',
            name='credit_text',
            field=models.CharField(blank=True, default='Designed & Developed by Vetri IT Systems', help_text='Small line under the copyright. The whole line is a link.', max_length=150, verbose_name='Credit text'),
        ),
        migrations.AddField(
            model_name='footer',
            name='show_credit',
            field=models.BooleanField(default=True, verbose_name='Show designer credit'),
        ),
    ]
