# Generated by Django 5.2.18 on 2026-10-09 14:03

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_footer_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cta_heading',
            field=models.CharField(blank=True, help_text='Shown above the BOOK NOW button under the videos, e.g. See MJ Shriram Live in London.', max_length=150, verbose_name='Booking strip heading'),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_venue',
            field=models.CharField(blank=True, help_text='Short venue for the booking strip, e.g. Cranford Suite, TW5 9PD. Leave empty to use the venue.', max_length=150, verbose_name='Booking strip venue (short)'),
        ),
        migrations.AddField(
            model_name='event',
            name='reels_heading',
            field=models.CharField(blank=True, help_text='e.g. Experience MJ Shriram. The block shows when this event has at least one video below.', max_length=150, verbose_name='Video section heading'),
        ),
        migrations.AddField(
            model_name='event',
            name='reels_intro',
            field=models.TextField(blank=True, verbose_name='Video section intro'),
        ),
        migrations.AddField(
            model_name='event',
            name='reels_more_handle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Watch more line - Instagram name'),
        ),
        migrations.AddField(
            model_name='event',
            name='reels_more_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Watch more line - link'),
        ),
        migrations.AddField(
            model_name='event',
            name='reels_more_text',
            field=models.CharField(blank=True, help_text='e.g. Watch more MJ Shriram performances on. Leave empty to hide the line.', max_length=150, verbose_name='Watch more line - text'),
        ),
        migrations.CreateModel(
            name='EventReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('link', models.URLField(help_text='Opens in a new tab.', max_length=500, verbose_name='Instagram Reel link')),
                ('cover', models.ImageField(blank=True, help_text='Portrait (9:16) cover of the video, about 360x640 px.', max_length=500, storage=core.storage.CloudinaryOrLocalStorage('events'), upload_to='events', verbose_name='Cover image')),
                ('cover_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Cover description')),
                ('caption', models.CharField(blank=True, help_text='Optional short line on the card. Extra videos (3rd onwards) use it as the link text.', max_length=100, verbose_name='Caption')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='core.event')),
            ],
            options={
                'verbose_name': 'Performance video',
                'verbose_name_plural': 'Performance videos (first 2 shown as cards, the rest as small links)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
