# Generated by Django 5.2.18 on 2026-10-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mj_shriram_reels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreel',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Performance video', 'verbose_name_plural': 'Performance videos (first 3 shown as cards, the rest as small links)'},
        ),
        migrations.AlterField(
            model_name='eventreel',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional short line on the card. Extra videos (4th onwards) use it as the link text.', max_length=100, verbose_name='Caption'),
        ),
    ]
